# Generated by Django 4.2 on 2026-05-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landa_library', '0001_initial'),
        ('landa_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroupCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày phân')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người phân')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='landa_library.documentcategory', verbose_name='Danh mục tài liệu')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='landa_groups.subgroup', verbose_name='Sub Group')),
            ],
            options={
                'verbose_name': 'Sub Group Category Assignment',
                'verbose_name_plural': 'Sub Group Category Assignments',
                'indexes': [models.Index(fields=['subgroup', 'category'], name='landa_group_subgrou_7da643_idx'), models.Index(fields=['category'], name='landa_group_categor_2a2468_idx')],
                'unique_together': {('subgroup', 'category')},
            },
        ),
    ]
