# Generated by Django 5.2.11 on 2026-05-11 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landa_library', '0002_add_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, help_text='CourseKey dạng course-v1:Org+Number+Run', max_length=255, unique=True, verbose_name='Course ID')),
                ('confirm_enabled', models.BooleanField(default=False, verbose_name='Bật Confirm Modal')),
                ('confirm_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Tiêu đề Confirm Modal')),
                ('confirm_description', models.TextField(blank=True, default='', verbose_name='Mô tả Confirm Modal')),
                ('confirm_checkbox_text', models.CharField(blank=True, default='', max_length=500, verbose_name='Nội dung checkbox xác nhận')),
                ('completion_enabled', models.BooleanField(default=False, verbose_name='Bật Completion Modal')),
                ('completion_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Tiêu đề Completion Modal')),
                ('completion_description', models.TextField(blank=True, default='', verbose_name='Mô tả Completion Modal')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Modal Config',
                'verbose_name_plural': 'Course Modal Configs',
            },
        ),

        migrations.AddField(
            model_name='coursemodalconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật gần nhất'),
        ),
    ]
