# Generated by Django 5.2.11 on 2026-05-12 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landa_library', '0003_coursemodalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên folder')),
                ('slug', models.SlugField(help_text='URL-friendly, auto-gen từ title', max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Lucide icon name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Folder',
                'verbose_name_plural': 'Help Folders',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(help_text='Unique trong folder', max_length=300)),
                ('content', models.TextField(blank=True, default='', verbose_name='Nội dung HTML')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự trong folder')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Đã xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Help Page',
                'verbose_name_plural': 'Help Pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='helpfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_folders_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_pages_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='landa_library.helpfolder', verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='helppage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_pages_updated', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa gần nhất'),
        ),
        migrations.AddIndex(
            model_name='helppage',
            index=models.Index(fields=['folder', 'sort_order'], name='landa_libra_folder__a1025e_idx'),
        ),
        migrations.AddIndex(
            model_name='helppage',
            index=models.Index(fields=['is_published', 'folder'], name='landa_libra_is_publ_8d9900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helppage',
            unique_together={('folder', 'slug')},
        ),
    ]
