# Generated by Django 4.2.11 on 2026-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landa_library', '0004_help_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodalconfig',
            name='welcome_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật Welcome Modal'),
        ),
        migrations.AddField(
            model_name='coursemodalconfig',
            name='welcome_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tiêu đề Welcome Modal'),
        ),
        migrations.AddField(
            model_name='coursemodalconfig',
            name='welcome_description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả Welcome Modal'),
        ),
    ]
