# Generated by Django 4.2.11 on 2026-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landa_library', '0005_add_welcome_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodalconfig',
            name='completion_social_type',
            field=models.CharField(blank=True, choices=[('zaloOA', 'Zalo OA'), ('facebook', 'Facebook'), ('website', 'Website'), ('instagram', 'Instagram')], default='', max_length=20, verbose_name='Loại mạng xã hội'),
        ),
        migrations.AddField(
            model_name='coursemodalconfig',
            name='completion_social_link',
            field=models.URLField(blank=True, default='', verbose_name='Link mạng xã hội'),
        ),
    ]
