# Generated by Django 3.2 on 2026-05-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landa_library', '0006_add_completion_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(db_index=True, max_length=100, verbose_name='Badge ID')),
                ('is_shown', models.BooleanField(default=False, verbose_name='Đã hiển thị chúc mừng')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đạt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge_id')},
            },
        ),
    ]
