# Generated by Django 3.2 on 2026-05-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landa_library', '0007_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseModalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID')),
                ('welcome_shown', models.BooleanField(default=False, verbose_name='Đã hiện Welcome')),
                ('confirm_shown', models.BooleanField(default=False, verbose_name='Đã hiện Confirm')),
                ('complete_shown', models.BooleanField(default=False, verbose_name='Đã hiện Complete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modal_states', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Course Modal State',
                'verbose_name_plural': 'Course Modal States',
                'unique_together': {('user', 'course_id')},
            },
        ),
    ]
