# Generated by Django 3.2 on 2026-05-14 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landa_library', '0008_usercoursemodalstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID')),
                ('section_id', models.CharField(max_length=255, verbose_name='Section Block ID', help_text='Block ID của chapter, vd: block-v1:Org+Num+Run+type@chapter+block@xxx')),
                ('enabled', models.BooleanField(default=False, verbose_name='Bật popup khích lệ')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Tiêu đề modal')),
                ('description', models.TextField(blank=True, default='', verbose_name='Nội dung khích lệ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Section Modal Config',
                'verbose_name_plural': 'Section Modal Configs',
                'unique_together': {('course_id', 'section_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSectionModalShown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255, verbose_name='Course ID')),
                ('section_id', models.CharField(max_length=255, verbose_name='Section Block ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm xem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_modal_shown', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'User Section Modal Shown',
                'verbose_name_plural': 'User Section Modal Shown',
                'unique_together': {('user', 'course_id', 'section_id')},
            },
        ),
    ]
